telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://volkovfamilybot-imistrafik.amvera.io/"
  bot-name: "@VolkovFamilyBot"
  bot-token: "5804740422:AAHFTWY92HNNSbAUGbYm4pA7oYFqUmqi1TM"